# Generated by Django 5.0.6 on 2026-02-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_otpverification_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="otp_code",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
