# Generated by Django 5.0.6 on 2026-02-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='qr_scanned_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
